CovidDetector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls"))
]

main/urls.py
from django.urls import path
from main import views
from django.conf import settings 
from django.conf.urls.static import static 
from .views import *

urlpatterns = [
    path('', views.index, name = 'index'),
]

if settings.DEBUG: 
    print('settings.debug is also true')
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

main/models.py
from django.db import models

# Create your models here.
class Xray(models.Model):
    scan = models.ImageField(upload_to = 'images/')

main/forms.py
from django import forms
from .models import *

class XrayForm(forms.ModelForm):

    class Meta:
        model = Xray
        fields = ['scan']

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import *
import matplotlib.pyplot as plt
import cv2
import numpy as np
from django.conf import settings 
from tensorflow.keras.models import *
import glob
import os

# Create your views here.
def predict(img_name):
    print('inside predict')
    # img_path = '/app/'+ '/media/images/' + img_name
    img_path = settings.BASE_DIR+ '/media/images/' + img_name
    img = cv2.imread(img_path)
    # model_path = '/app/' + '/static/main/ml/model.h5'
    model_path = settings.BASE_DIR + '/static/main/ml/model.h5'
    print('loading model')
    model = load_model(model_path)
    print('model loaded')
    img = cv2.resize(img, (224,224), interpolation = cv2.INTER_AREA)
    img = img/255
    img = np.reshape(img, (1,224,224,3))
    print('predicting, on img:', img.shape)
    prob = model.predict(img)[0][0]
    prob = "{0:.2f}".format(prob) 
    prob = float(prob)
    if prob > 0.5 : 
        pred = 1
    else:
        pred = 0
    print(str(img_name), prob)
    print('going to return')  
    if pred == 1:
        return "Covid-19 Positive", prob
    else :
        return "Covid-19 Negative", prob

def index(request):
    print('inside index')
    error = None
    if request.method == 'POST': 
        form = XrayForm(request.POST, request.FILES) 
        print('POST request recieved.')
        if form.is_valid(): 
            print('saving img')
            with open('media/images/xray.jpg', 'wb+') as destination:
                for chunk in request.FILES['scan'].chunks():
                    destination.write(chunk)
            name = 'xray.jpg'
            print('saved:',name)
            # form.save() 
            print('calling predict')
            result, prob = predict(name)
            prob = float(prob)*100
            error = False
            return render(request, 'main/index.html', {'form':form, 'error':error, 'result':result, 'prob':prob, 'revprob':100 - prob})
        else:
            error = True
            message = "Unsupported Format"
            return render(request, 'main/index.html', {'form':form, 'error':error, 'message':message, 'result':None, 'prob':None})

    else:
        form = XrayForm()
    return render(request, 'main/index.html', {'form':form})
    # return HttpResponse('Hello, This is my Covid-19 Detector.')

templates/main/index.html
{% extends "main/layouts/base.html" %}
{% load static %}

{% block content %}
<div class="parallax-container">
    <div class="parallax"><img src="{% static 'main/images/robot-2.jpg' %}"></div>
    <div class="container">
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row ">
            <div class="col s12 m3"></div>
            <div class="col s12 m6">
                <div class="card transparent">
                    <div class="card-content">
                        <form method="POST" enctype="multipart/form-data">
                            {%csrf_token%}
                            <div class="file-field input-field">
                                <div class="btn waves-effect waves-light blue lighten-2"><i
                                        class="material-icons">file_upload</i>
                                    <input required type="file" name="scan" id="id_scan">
                                </div>

                                <div class="file-path-wrapper">
                                    <input class="file-path validate transparent" type="text">
                                </div>

                                <button class="btn waves-effect waves-light blue lighten-2 right" type="submit"
                                    name="action">Predict
                                    <i class="material-icons right">arrow_forward</i>
                                </button>
                            </div>
                        </form>
                        {% if error is None %}
                        <p class="white-text">Upload an X-Ray scan</p>
                        {% elif error is True %}
                        <p class="red-text">**{{message}}**</p>
                        {% else %}
                        <p class="white-text">Prediction: </p>
                        {% if prob > 50 %}
                        <p class="red-text">{{result}}</p>
                        {%else%}
                        <p class="green-text">{{result}}</p>
                        {%endif%}
                        <a class="waves-effect waves-light btn modal-trigger blue lighten-2" href="#modal1">
                            Show Result</a>
                        <div id="modal1" class="modal">
                            <div class="modal-content">
                                <h4>Result</h4>
                                <div class="container"></div>
                                {% if prob > 50 %}
                                <div class="row">
                                    <p class="red-text">Prediction: {{result}}</p>
                                </div>
                                <div class="row">
                                    <p>Probability that person is infected: {{prob}}%</p>
                                </div>
                                <div class="row">
                                    <div class="col s3">
                                        <p class="left-align">Healthy</p>
                                    </div>
                                    <div class="col s6"></div>
                                    <div class="col s3">
                                        <p class="right-align">Infected</p>
                                    </div>
                                </div>
                                <div class="progress">
                                    <div class="determinate red " style="width: {{prob}}%"></div>
                                </div>
                                {% else %}
                                <div class="row">
                                    <p class="green-text">Prediction: {{result}}</p>
                                </div>
                                <div class="row">
                                    <p>Probability that person is not infected: {{revprob}}%</p>
                                </div>
                                <div class="row">
                                    <div class="col s3">
                                        <p class="left-align">Healthy</p>
                                    </div>
                                    <div class="col s6"></div>
                                    <div class="col s3">
                                        <p class="right-align">Infected</p>
                                    </div>
                                </div>
                                <div class="progress">
                                    <div class="determinate blue lighten-2" style="width: {{prob}}%"></div>
                                </div>
                                {% endif %}
                            </div>

                            <div class="modal-footer">
                                <a href="#!" class="modal-close waves-effect waves-green btn-flat">OK</a>
                            </div>
                        </div>
                    </div>
                    <script>
                        document.addEventListener('DOMContentLoaded', function () {
                            var Modalelem = document.querySelector('.modal');
                            var instance = M.Modal.init(Modalelem);
                            instance.open();
                        });

                    </script>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
</div>


<div class="container blue lighten-2">
    <div class="row">
        <div class="col l6 s12">
            <h5 class="grey-text text-lighten-4 font-serif">About the Model</h5>
            <p class="grey-text text-lighten-4 font-serif"> It is a Deep Neural Network model which consists of
                2D-Convolution and Dense Layers
                with over 1 million trained parameters and accuracy of 97.7%.
                It is built on <a class="red-text text-lighten-4 font-serif" href="http://keras.io">Keras</a>
                and <a class="red-text text-lighten-4 font-serif" href="http://tensorflow.org">Tensorflow</a>
                as backend.
            </p>
        </div>
        <div class="col l6 s4">
            <img class="responsive-img" src="{% static 'main/images/keras.jpg' %}" alt="">
        </div>
    </div>
</div>
<div class="parallax-container">
    <div class="parallax"><img class="responsive-img" src="{% static 'main/images/coronavirus.jpg' %}"></div>
</div>

<div class="container blue lighten-2">
    <div class="row"></div>
    <div class="row">
        <div class="col l8 s12">
            <h5 class="grey-text text-lighten-4 font-serif">About Covid-19</h5>
            <p class="grey-text text-lighten-4 font-serif"> Coronavirus disease (COVID-19) is an
                infectious disease caused by a newly discovered coronavirus.The virus that
                causes COVID-19 is mainly transmitted through droplets generated when an
                infected person coughs, sneezes, or exhales. These droplets are too heavy
                to hang in the air, and quickly fall on floors or surfaces.
                You can be infected by breathing in the virus if you are within close
                proximity of someone who has COVID-19, or by touching a contaminated
                surface and then your eyes, nose or mouth.
                <a class="red-text text-lighten-4 font-serif"
                    href="https://www.who.int/emergencies/diseases/novel-coronavirus-2019">More info...</a>
            </p>
        </div>
        <div class="col l4 s4">
            <img class="responsive-img" src="{% static 'main/images/giphy11.gif' %}" alt="">
        </div>
    </div>
</div>

<div class="parallax-container">
    <div class="parallax"><img class="responsive-img" src="{% static 'main/images/chest-xray.jpg' %}"></div>
</div>

<div class="container blue lighten-2">
    <div class="row"></div>
    <div class="row">
        <div class="col l9 s12">
            <h5 class="grey-text text-lighten-4 font-serif">About Dataset</h5>
            <p class="grey-text text-lighten-4 font-serif"> The dataset for Model was collected
                and compiled from famous public data source platforms:
                <a class="red-text text-lighten-4 font-serif"
                    href="https://github.com/ieee8023/covid-chestxray-dataset/tree/master/images">Github</a>
                and <a class="red-text text-lighten-4 font-serif"
                    href="https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia">kaggle</a>.
                A descent distortion and augmentation was applied on images before training. This was done
                to prevent overfitting as data was quite small and chances of overfitting were very high.
            </p>
        </div>
        <div class="col l3 s4">
            <img class="responsive-img" src="{% static 'main/images/xray1.jpg' %}" alt="">
        </div>
    </div>
</div>

{% endblock %}

templates/main/index2.html
{% extends "main/layouts/base.html" %}
{% load static %}

{% block content %}
<div class="parallax-container">
    <div class="parallax"><img src="{% static 'main/images/robot-2.jpg' %}"></div>
    <div class="container">
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row"></div>
        <div class="row ">
            <div class="col s12 m3"></div>
            <div class="col s12 m6">
                <div class="card transparent">
                    <div class="card-content">
                        <form method = "post" enctype="multipart/form-data"> 
                            {% csrf_token %} 
                            {{ form.as_p }} 
                            <button type="submit">Upload</button> 
                        </form> 
                        <p>Upload an X-ray</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/main/layouts/base.html
<!DOCTYPE html>
<html>

<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css" media="screen,projection" />

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body style="background-color: #64b5f6">
    {% load static %}
    <nav class="blue lighten-2">
        <div class="container">
            <div class="nav-wrapper">
                <a style="font-size:2vw;" class="brand-logo "> Covid-19 Online Detection from Chest X-Ray using Deep Learning</a>
            </div>
        </div>
    </nav>
    {% block content %} {% endblock %}
    <footer class="page-footer  blue lighten-2">
        <div class="container ">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="grey-text text-lighten-4 font-serif">Project created by Gaurav Verma</h5>
                    <h7>Connect With Me</h7>

                </div>
            </div>
            <div class="row">
                <div class="col  s4">
                    <a class="grey-text text-lighten-3 waves-effect waves-light font-serif"
                        href="https://github.com/gauravv0412">
                        Github
                        <div class="col s2">
                            <a class="grey-text text-lighten-3 waves-effect waves-light font-serif"
                                href="https://github.com/gauravv0412">
                                <img class="responsive-img" src="{% static 'main/icons/github.png' %}" alt="*"
                                    class="circle responsive-img"> <!-- notice the "circle" class -->
                            </a>
                        </div>
                    </a>
                </div>
                <div class="col  s4">
                    <a class="grey-text text-lighten-3 waves-effect waves-light font-serif"
                        href="https://www.linkedin.com/in/gaurav-verma-76927b160/">
                        Linkedin
                        <div class="col s2">
                            <a class="grey-text text-lighten-3 waves-effect waves-light font-serif"
                                href="https://www.linkedin.com/in/gaurav-verma-76927b160/">
                                <img src="{% static 'main/icons/lnkd.png' %}" alt="*" class="circle responsive-img">
                                <!-- notice the "circle" class -->
                            </a>
                        </div>
                    </a>
                </div>
                <div class="col  s4">
                    <a class="grey-text text-lighten-3 waves-effect waves-light font-serif"
                        href="https://www.facebook.com/profile.php?id=100003041872853">
                        Facebook </a>
                    <div class="col s2">
                        <a class="grey-text text-lighten-3 waves-effect waves-light font-serif"
                            href="https://www.facebook.com/profile.php?id=100003041872853">
                            <img class="responsive-img" src="{% static 'main/icons/fb.png' %}" alt="*"
                                class="circle responsive-img"> <!-- notice the "circle" class -->
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                Copyright Text © 2020 Gaurav Verma
            </div>
        </div>
    </footer>

    <script>
        M.AutoInit();
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.dropdown-trigger');
            var instances = M.Dropdown.init(elems, { "coverTrigger": false, "constrainWidth": false });
        });
    </script>

</body>

</html>